# Generated by Django 3.1.7 on 2023-03-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myrestaurant', '0003_ingredient_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientitem',
            name='unit',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
